name: Deploy

env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      HOST: 88.218.28.244
      USERNAME: root
      PASSWORD: ${{ secrets.SSH_PASSWORD }}
      PORT: 22

    steps:

      - name: Stop server
        uses: appleboy/ssh-action@master
        with:
          host: HOST
          username: USERNAME
          password: PASSWORD
          port: PORT
          script: |
            if screen -list | grep -q "${{ env.REPOSITORY_NAME }}"; then
              screen -X -S ${{ env.REPOSITORY_NAME }} quit;
            fi

      - name: Pull changes
        uses: appleboy/ssh-action@master
        with:
          host: HOST
          username: USERNAME
          password: PASSWORD
          port: PORT
          script: |
            cd ~/${{ env.REPOSITORY_NAME }}
            git pull origin main

      - name: Setup
        uses: appleboy/ssh-action@master
        with:
          host: HOST
          username: USERNAME
          password: PASSWORD
          port: PORT
          script: |
            cd ~/${{ env.REPOSITORY_NAME }}
            echo '${{ secrets.ENV }}' > ~/${{ env.REPOSITORY_NAME }}/.env
            npm install

      - name: Run
        uses: appleboy/ssh-action@master
        with:
          host: HOST
          username: USERNAME
          password: PASSWORD
          port: PORT
          script: screen -S ${{ env.REPOSITORY_NAME }} -d -m node ~/${{ env.REPOSITORY_NAME }}